// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbY-r__OnJaznh7COe6X2BoMDkhEJPQfc',
    appId: '1:13139605846:web:0689ad9493fbecd7993ef7',
    messagingSenderId: '13139605846',
    projectId: 'writer-profile',
    authDomain: 'writer-profile.firebaseapp.com',
    storageBucket: 'writer-profile.firebasestorage.app',
    measurementId: 'G-M95J5PHY57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA49-SZC570OIlV2r89ZIQ9GsMrdaLwk-E',
    appId: '1:13139605846:android:72891ad5b2bb59eb993ef7',
    messagingSenderId: '13139605846',
    projectId: 'writer-profile',
    storageBucket: 'writer-profile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1Ao5Mjw9M1gev19FjjFiN3x3NusQShk',
    appId: '1:13139605846:ios:ac52a209485bf7ce993ef7',
    messagingSenderId: '13139605846',
    projectId: 'writer-profile',
    storageBucket: 'writer-profile.firebasestorage.app',
    iosBundleId: 'com.writerprofile.writerProfile',
  );
}
